exclude: orgs/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-vcs-permalinks
      - id: check-shebang-scripts-are-executable
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: debug-statements
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.282'
    hooks:
      - id: ruff
        args: [--line-length=140, --fix, --exit-non-zero-on-fix]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^orgs/
        args: ["--config", ".black"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^orgs/
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [types-PyYAML, types-requests, types-python-dateutil>=2.8.19]
 